Login_URL: http://192.168.1.63:8080/login.html
Test_Data: testdata.xml
SanYaoSu_Test_Data: test_sanyaosu_A.xlsx
log:
     file_name: test_zhi_liao.log
     backup: 5
     console_level: WARNING
     file_level: DEBUG
     pattern: '%(asctime)s-%(name)s- [%(levelname)s] -%(message)s'