Login_URL: http://192.168.1.63:8080/login.html
Login_Test_Data: test_login_A.xlsx   #test_login_B.xlsx   test_login_A.xlsx
SanYaoSu_Test_Data: test_sanyaosu_A.xlsx #test_sanyaosu_B.xlsx  test_sanyaosu_A.xlsx
log:
     file_name: test_zhi_liao.log
     backup: 5
     console_level: WARNING
     file_level: DEBUG
     pattern: '%(asctime)s-%(name)s- [%(levelname)s] -%(message)s'